# Generated by Django 4.2.3 on 2023-08-20 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/img-course/')),
                ('video', models.FileField(blank=True, null=True, upload_to='%Y/%m/%d/video-course/')),
                ('hit', models.BigIntegerField(default=0)),
                ('price', models.BigIntegerField(default=0)),
                ('status', models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=True)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='category.category')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Epizode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('lid', models.TextField(blank=True)),
                ('number', models.BigIntegerField(default=0)),
                ('status', models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=True)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epizodes', to='learn.course')),
            ],
            options={
                'verbose_name': 'Epizode',
                'verbose_name_plural': 'Epizodes',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('description', models.TextField(blank=True)),
                ('status', models.BooleanField(choices=[(True, 'active'), (False, 'inactive')], default=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='%Y/%m/%d/video-lessons/')),
                ('voice', models.FileField(blank=True, null=True, upload_to='%Y/%m/%d/voice/')),
                ('hit', models.BigIntegerField(default=0)),
                ('is_free', models.BooleanField(choices=[(True, 'free'), (False, 'cash')], default=False)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('epizode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learn.epizode')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
    ]
